# Generated by Django 4.2 on 2024-02-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UerProfile",
        ),
    ]
