# Generated by Django 4.2 on 2024-02-02 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("is_driver", models.BooleanField(default=False)),
                ("vehicle_type", models.CharField(default="", max_length=10)),
                (
                    "license_number",
                    models.CharField(default="", max_length=20, unique=True),
                ),
                (
                    "max_passenger_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
            ],
        ),
    ]
