# Generated by Django 4.2 on 2024-02-02 14:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0003_alter_userprofile_max_passenger_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("luxury", "Luxury"),
                    ("suv", "SUV"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
