# Generated by Django 4.2 on 2024-02-07 00:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0006_trip_is_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="vehicle_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("any", "Any"),
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("luxury", "Luxury"),
                    ("suv", "SUV"),
                ],
                default="any",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
