# Generated by Django 4.2 on 2024-02-07 00:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0007_trip_vehicle_type_alter_userprofile_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="vehicle_type",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("any", "Any"),
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("luxury", "Luxury"),
                    ("suv", "SUV"),
                ],
                default="any",
                max_length=50,
            ),
        ),
    ]
