# Generated by Django 4.2 on 2024-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0008_alter_trip_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
