# Generated by Django 4.2 on 2024-02-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0009_trip_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips_as_driver",
                to="signup.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
