# Generated by Django 4.2 on 2024-02-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0010_trip_driver_profile_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Opening", "Opening"),
                    ("Confirmed", "Confirmed"),
                    ("Completed", "Completed"),
                ],
                default="Opening",
                max_length=10,
            ),
        ),
    ]
