# Generated by Django 4.2 on 2024-02-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0011_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
