# Generated by Django 4.2 on 2024-02-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0012_alter_trip_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="shared_passenger",
            field=models.ManyToManyField(
                blank=True, related_name="shared_trips", to="signup.userprofile"
            ),
        ),
    ]
