# Generated by Django 4.2 on 2024-02-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0013_trip_shared_passenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("luxury", "Luxury"),
                    ("suv", "SUV"),
                ],
                default="economy",
                max_length=20,
            ),
        ),
    ]
